--1

SELECT * 
FROM MOVIES

--2

SELECT *
FROM GENRES

--3

SELECT *
FROM STUDIOS 
WHERE STUDIO_ACTIVE=1
--4

SELECT MEMBER_NAME 
FROM MEMBERS 
ORDER BY MEMBER_NAME DESC 
LIMIT 20

--5

SELECT MOVIE_DURATION, COUNT(*) FRECUENCY
FROM MOVIES
GROUP BY  DURATION 
GROUP BY FRECUENCY DESC
LIMIT 20

--6

SELECT *
FROM MOVIES
WHERE  UPPER(MOVIE_NAME) LIKE 'A%' AND YEAR (MOVIE_LAUNCH_DATE)>=2000

--7

SELECT ACTOR_NAME
FROM ACTORS
WHERE MONTH(ACTOR_BIRTH_DATE)=06

--8

SELECT DIRECTOR_NAME,DIRECTOR_BIRTH_DATE
FROM DIRECTORS
WHERE 2024 -YEAR(DIRECTOR_BIRTH_DATE)<=50 AND DIRECTOR_DEAD_DATE IS NULL

--9

SELECT DIRECTOR_NAME,DIRECTOR_BIRTH_DATE
FROM DIRECTORS
WHERE 2024 -YEAR(DIRECTOR_BIRTH_DATE)<=50 AND DIRECTOR_DEAD_DATE IS NOT NULL

--10

SELECT DIRECTOR_NAME,DIRECTOR_BIRTH_DATE
FROM DIRECTORS
WHERE 2024 -YEAR(DIRECTOR_BIRTH_DATE)<=40 AND DIRECTOR_DEAD_DATE IS NULL

--11

SELECT AVG(DIRECTOR_BIRTH_DATE)
FROM directors
WHERE DIRECTOR_DEAD_DATE IS NULL

--12

SELECT AVG(DIRECTOR_BIRTH_DATE)
FROM directors
WHERE DIRECTOR_DEAD_DATE IS NOT NULL

--14

SELECT  DISTINCT MOVIE_NAME,STUDIO_NAME
FROM MOVIES,STUDIOS
INNER JOIN MOVIES ON MOVIES.STUDIO_ID=STUDIOS.STUDIO_ID 

--15

SELECT DISTINCT MEMBER_NAME
FROM MEMBERS
INNER JOIN MEMBERS_MOVIE_RENTAL ON MEMBERS.MEMBER_ID = MEMBERS_MOVIE_RENTAL.MEMBER_ID
WHERE YEAR(MEMBER_RENTAL_DATE) BETWEEN 2010 AND 2015;

--16

SELECT NATIONALITIES.NATIONALITY_NAME, COUNT(MOVIES.NATIONALITY_ID) 
FROM NATIONALITIES
INNER JOIN MOVIES ON NATIONALITIES.NATIONALITY_ID = MOVIES.NATIONALITY_ID
GROUP BY NATIONALITIES.NATIONALITY_NAME;

--17

SELECT MOVIE_NAME
FROM MOVIES
INNER JOIN GENRES ON MOVIES.GENRE_ID = GENRES.GENRE_ID
WHERE GENRE_NAME = 'Documentary'
SELECT  *
FROM MOVIES 
WHERE GENRE_ID = (SELECT GENRE_ID FROM GENRES WHERE GENRE_NAME = 'Documentary')

--18

SELECT MOVIE_NAME
FROM MOVIES
INNER JOIN DIRECTORS ON MOVIES.DIRECTOR_ID = DIRECTORS.DIRECTOR_ID
WHERE YEAR(DIRECTORS.DIRECTOR_BIRTH_DATE) >= 1980 AND DIRECTORS.DIRECTOR_DEAD_DATE IS NULL;

--19

SELECT M.MEMBER_NAME,D.DIRECTOR_NAME, D.DIRECTOR_BIRTH_PLACE
FROM MEMBERS M
INNER JOIN DIRECTORS D ON M.MEMBER_TOWN = D.DIRECTOR_BIRTH_PLACE

--20

SELECT MOVIE_NAME, YEAR(MOVIE_LAUNCH_DATE) 
FROM MOVIES
INNER JOIN STUDIOS ON MOVIES.STUDIO_ID = STUDIOS.STUDIO_ID
WHERE STUDIO_ACTIVE = 0

--21

SELECT *
FROM MOVIES
INNER JOIN PUBLIC.MEMBERS_MOVIE_RENTAL ON MEMBERS_MOVIE_RENTAL.MOVIE_ID = MOVIES.MOVIE_ID
ORDER BY MEMBER_RENTAL_DATE DESC 
LIMIT 10;

--22

SELECT COUNT(MOVIE_NAME),DIRECTOR_NAME
FROM MOVIES,DIRECTORS
INNER JOIN MOVIES ON MOVIES.DIRECTOR_ID=DIRECTORS.DIRECTOR_ID
WHERE YEAR(DIRECTOR_BIRTH_DATE)<41

--23


